ConexionLINQ/Controllers/AgricultorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConexionLINQ.Models;

namespace ConexionLINQ.Controllers
{
    public class AgricultorController : Controller
    {

        private PepinoDataContext context;
        public AgricultorController()
        {
            context = new PepinoDataContext();
        }
        // GET: Agricultor

        public ActionResult Index()
        {
            IList<AgricultorModel> agricultorList = new List<AgricultorModel>();
            var query = from Agricultor in context.Agricultors
                        select Agricultor;
            var agricultors = query.ToList();
            foreach (var agricultorData in agricultors)
            {
                agricultorList.Add(new AgricultorModel()
                {
                    Id = agricultorData.Id,
                    Nombre = agricultorData.Nombre,
                    Poblacion = agricultorData.Población,
                    CP = agricultorData.CP
                });
            }
            return View(agricultorList);
        }


        public ActionResult Create()
        {
            AgricultorModel model = new AgricultorModel();
            return View(model);
        }


        [HttpPost]
        public ActionResult Create(AgricultorModel model)
        {
            try
            {
                Agricultor agricultor = new Agricultor()
                {
                    Nombre = model.Nombre,
                    Población = model.Poblacion,
                    CP = model.CP
                };
                context.Agricultors.InsertOnSubmit(agricultor);
                context.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

    }
}

ConexionLINQ/Controllers/UsuarioController.cs
using ConexionLINQ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ConexionLINQ.Controllers
{
    public class UsuarioController : Controller
    {

        //http://stackoverflow.com/questions/23448510/linq-to-sql-authenticate-login-credentials
        //https://msdn.microsoft.com/en-us/library/ms178581.aspx

        private PepinoDataContext context;
        public UsuarioController()
        {
            context = new PepinoDataContext();
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }
        // GET: Usuario/CreateUsuario
        public ActionResult CreateUsuario()
        {
            RegisterModel model = new RegisterModel();
            return View(model);
        }

        // POST: /Usuario/CreateUsuario

        [HttpPost]
        public ActionResult CreateUsuario(RegisterModel model)
        {
            try
            {
                if (model.Password == model.ConfirmPassword) { 
                Usuario obj = new Usuario
                {

                    //Id = model.Id,
                    Email = model.Email,
                    Nickname = model.Nickname,
                    Password = model.Password

                };

                context.Usuarios.InsertOnSubmit(obj);
                context.SubmitChanges();
                }

                return RedirectToAction("Index","Pepino");
                
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Usuario/CreateUsuario
        public ActionResult Login()
        {
            LoginModel model = new LoginModel();
            return View(model);
        }
        // POST: Usuario/CreateUsuario
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            {
                Usuario usu = (from u in context.Usuarios
                                   where u.Email.Equals(model.Email) &&
                                   u.Password.Equals(model.Password)
                                   select u).Single();

                //Session["mail"] = usu.Email;

                if (usu != null)
                {
                    FormsAuthentication.SetAuthCookie(usu.Email,false);

                    return RedirectToAction("Index", "Pepino");
                }
                return RedirectToAction("Login");
            }
        }
        // Usuario/Logout
        public ActionResult Logout()
        {
            //Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }



    }
}

ConexionLINQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PepinoAPP - @ViewBag.Title</title>
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pepino Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>-->
                    

                    
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    

                    @{
                        if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Pepinos", "Index", "Pepino")</li>
                            <li>@Html.ActionLink("Agricultores", "Index", "Agricultor")</li>
                            <li>@Html.ActionLink("LogOut", "Logout", "Usuario")</li>
                        }

                        else
                        {
                            <li>@Html.ActionLink("Registrar", "CreateUsuario", "Usuario")</li>
                            <li>@Html.ActionLink("LogIn", "Login", "Usuario")</li>
                        }
                    }

                   
                </ul>
               
                
                        
                   
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        <p>@Context.User.Identity.Name</p>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PepinoAPP</p>
        </footer>
    </div>

  
        <link href="~/Content/Site.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</body>
</html>